import { PrismaClient } from "@prisma/client";
import bcrypt from "bcryptjs";

const prisma = new PrismaClient();

async function main() {
  if (process.env.NODE_ENV === "production" && process.env.ALLOW_SEED !== "true") {
    console.error("❌ SAFETY ALERT: Seeding is blocked in production to prevent accidental data loss. Set ALLOW_SEED=true to override.");
    process.exit(1);
  }

  console.log("🌙 Seeding Midnight Fuel Database with complete updated menu items...");

  // 1. Clear existing data in reverse relation order
  await prisma.notification.deleteMany();
  await prisma.orderDeliveryChargeHistory.deleteMany();
  await prisma.orderComboItem.deleteMany();
  await prisma.orderCombo.deleteMany();
  await prisma.invoice.deleteMany();
  await prisma.payment.deleteMany();
  await prisma.orderItem.deleteMany();
  await prisma.order.deleteMany();
  await prisma.comboPriceHistory.deleteMany();
  await prisma.comboItem.deleteMany();
  await prisma.combo.deleteMany();
  await prisma.deliveryDistanceSlab.deleteMany();
  await prisma.priceHistory.deleteMany();
  await prisma.product.deleteMany();
  await prisma.category.deleteMany();
  await prisma.address.deleteMany();
  await prisma.customer.deleteMany();
  await prisma.admin.deleteMany();
  await prisma.businessSettings.deleteMany();

  // 2. Seed Admin User
  const passwordHash = await bcrypt.hash("MidnightFuel@2026", 10);
  const admin = await prisma.admin.create({
    data: {
      name: "Midnight Fuel Admin",
      username: "admin",
      passwordHash,
      role: "SUPER_ADMIN",
    },
  });
  console.log(`✅ Admin created: username = ${admin.username}`);

  // 3. Seed Business Settings
  const settings = await prisma.businessSettings.create({
    data: {
      id: "default-settings",
      businessName: "Midnight Fuel",
      tagline: "EAT • ENJOY • RECHARGE",
      logoUrl: "/images/logo.png",
      phone: "+91 90801 39363",
      whatsapp: "+91 90801 39363",
      address: "123 Food Street, Late Night Hub, Tirunelveli - 627001",
      city: "Tirunelveli",
      openingTime: "19:00",
      closingTime: "02:00",
      minOrderAmount: 199,
      upiId: "midnightfuel@upi",
      isCashEnabled: true,
      isUpiEnabled: true,
      currency: "INR",
      timezone: "Asia/Kolkata",
      storeMode: "AUTO",
      isForceOpen: false,
      isForceClosed: false,
    },
  });
  console.log(`✅ Business Settings initialized (${settings.businessName})`);

  // 4. Seed Delivery Distance Slabs
  const slabsData = [
    { minDistanceKm: 0, maxDistanceKm: 2, defaultCharge: 30, displayOrder: 1 },
    { minDistanceKm: 2, maxDistanceKm: 4, defaultCharge: 40, displayOrder: 2 },
    { minDistanceKm: 4, maxDistanceKm: 6, defaultCharge: 60, displayOrder: 3 },
    { minDistanceKm: 6, maxDistanceKm: 8, defaultCharge: 80, displayOrder: 4 },
    { minDistanceKm: 8, maxDistanceKm: 10, defaultCharge: 100, displayOrder: 5 },
  ];

  for (const s of slabsData) {
    await prisma.deliveryDistanceSlab.create({ data: s });
  }
  console.log(`✅ ${slabsData.length} Delivery Distance Slabs seeded`);

  // 5. Seed Categories
  const categoriesData = [
    {
      name: "BIRIYANI & MANDHI",
      slug: "biriyani-and-mandhi",
      description: "Authentic Hyderabadi dum biriyanis, bucket feasts, and Yemeni spiced slow-roasted mandhi platters",
      image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80",
      order: 1,
    },
    {
      name: "SHAWARMA",
      slug: "shawarma",
      description: "Flavourful slow-turned spit-roasted & fried chicken wraps in soft kubbos and rumali rotti",
      image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&auto=format&fit=crop&q=80",
      order: 2,
    },
    {
      name: "CHICKEN & WINGS",
      slug: "chicken-and-wings",
      description: "Alfaham, Grill, Tandoori, Kanthari, Crispy Fried Chicken, Strips and sizzling Honey Wings",
      image: "https://images.unsplash.com/photo-1527477321055-436158a2b0a5?w=800&auto=format&fit=crop&q=80",
      order: 3,
    },
    {
      name: "CHICKEN GRAVY & CURRY",
      slug: "chicken-gravy",
      description: "Rich Butter Chicken, Chettinadu, Chilli, Garlic, Ginger, and Pepper boneless gravies",
      image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&auto=format&fit=crop&q=80",
      order: 4,
    },
    {
      name: "FRIED RICE & NOODLES",
      slug: "fried-rice-and-noodles",
      description: "Wok-tossed Chicken, Egg, and Beef Fried Rice & Noodles served with creamy mayonnaise",
      image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&auto=format&fit=crop&q=80",
      order: 5,
    },
    {
      name: "BURGERS & SANDWICHES",
      slug: "burgers-and-sandwiches",
      description: "Crispy chicken burgers, sandwiches, keto no-bun double burgers & veg options",
      image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80",
      order: 6,
    },
    {
      name: "PIZZA, FRIES & SIDES",
      slug: "pizza-fries-and-sides",
      description: "Chicken Pizzas, Loaded Fries, French Fries, Rumali Rotti, Kubbos & Extra Dips",
      image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80",
      order: 7,
    },
    {
      name: "BEVERAGES",
      slug: "beverages",
      description: "Chilled energizing sparkling Red, Blue Curacao, and Green Mojitos",
      image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&auto=format&fit=crop&q=80",
      order: 8,
    },
  ];

  const categoryMap = new Map<string, string>();
  for (const cat of categoriesData) {
    const created = await prisma.category.create({
      data: cat,
    });
    categoryMap.set(cat.name, created.id);
  }
  console.log(`✅ ${categoriesData.length} Categories seeded`);

  // 6. Complete Organized Products List
  const productsData = [
    // ----------------------------------------------------
    // 1. BIRIYANI & MANDHI
    // ----------------------------------------------------
    {
      categoryName: "BIRIYANI & MANDHI",
      name: "Chicken Bucket Biriyani 5 person (Carrot halwa And onion Raitha)",
      slug: "chicken-bucket-biriyani-5-person",
      description: "Grand family bucket feast! Authentic Hyderabadi dum biriyani for 5 persons, served with sweet Carrot Halwa, rich Onion Raita, Brinjal gravy and boiled eggs.",
      price: 999,
      image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 30,
    },
    {
      categoryName: "BIRIYANI & MANDHI",
      name: "Hydrabad Chicken Biriyani",
      slug: "hydrabad-chicken-biriyani",
      description: "Authentic Hyderabadi dum biriyani layered with fragrant long-grain basmati rice, tender chicken, and royal spices. Served with raita and brinjal gravy.",
      price: 170,
      image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 20,
    },
    {
      categoryName: "BIRIYANI & MANDHI",
      name: "Hydrabad Alfaham Chicken Biriyani",
      slug: "hydrabad-alfaham-chicken-biriyani",
      description: "Smoky charcoal-grilled Alfaham chicken served atop rich, fragrant Hyderabadi dum biriyani rice with special accompaniments.",
      price: 230,
      image: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 25,
    },
    {
      categoryName: "BIRIYANI & MANDHI",
      name: "Hydrabad Grill Chicken Biriyani",
      slug: "hydrabad-grill-chicken-biriyani",
      description: "Juicy spice-crusted grilled quarter chicken served over aromatic Hyderabadi biriyani rice with mint dip.",
      price: 230,
      image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 25,
    },
    {
      categoryName: "BIRIYANI & MANDHI",
      name: "Hydrabad Tandoori Chicken Biriyani",
      slug: "hydrabad-tandoori-chicken-biriyani",
      description: "Clay-oven baked fiery red Tandoori chicken paired with spiced Hyderabadi biriyani rice for an explosion of flavours.",
      price: 230,
      image: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 25,
    },
    {
      categoryName: "BIRIYANI & MANDHI",
      name: "Hydrabad Kanthari Chicken Biriyani",
      slug: "hydrabad-kanthari-chicken-biriyani",
      description: "Bird's eye chili (Kanthari) infused fiery green marinated roasted chicken served with rich Hyderabadi biriyani rice.",
      price: 230,
      image: "https://images.unsplash.com/photo-1589302168068-964664d93dc0?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 25,
    },
    {
      categoryName: "BIRIYANI & MANDHI",
      name: "Hydrabad Peri peri Chicken Biriyani",
      slug: "hydrabad-peri-peri-chicken-biriyani",
      description: "Zesty Peri Peri spiced marinated chicken grilled to perfection over royal Hyderabadi dum biriyani.",
      price: 230,
      image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: false,
      preparationTime: 25,
    },
    {
      categoryName: "BIRIYANI & MANDHI",
      name: "Hydrabad Bbq Chicken Biriyani",
      slug: "hydrabad-bbq-chicken-biriyani",
      description: "Sweet and smoky BBQ glazed chicken quarter served over aromatic Hyderabadi dum biriyani rice.",
      price: 230,
      image: "https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: false,
      preparationTime: 25,
    },
    {
      categoryName: "BIRIYANI & MANDHI",
      name: "Alfaham Chicken Mandhi",
      slug: "alfaham-chicken-mandhi",
      description: "Smoky charcoal-grilled Arabian Alfaham chicken served over spiced aromatic Mandhi basmati rice with garlic sauce and tomato salsa.",
      price: 260,
      image: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 25,
    },
    {
      categoryName: "BIRIYANI & MANDHI",
      name: "Grill Chicken Mandhi",
      slug: "grill-chicken-mandhi",
      description: "Tender grilled quarter chicken seasoned with Yemeni spices over aromatic basmati mandhi rice, served with salsa and garlic toum.",
      price: 260,
      image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 25,
    },
    {
      categoryName: "BIRIYANI & MANDHI",
      name: "Kanthari Chicken Mandhi",
      slug: "kanthari-chicken-mandhi",
      description: "Spicy Kerala Kanthari (Bird's Eye Chili) roasted chicken served on traditional Arabic fragrant Mandhi rice with garlic toum and red sauce.",
      price: 270,
      image: "https://images.unsplash.com/photo-1633945274405-b6c8069047b0?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 25,
    },
    {
      categoryName: "BIRIYANI & MANDHI",
      name: "Peri Peri Chicken Mandhi",
      slug: "peri-peri-chicken-mandhi",
      description: "Fiery Peri-Peri spiced roasted chicken paired with fragrant Yemeni Mandhi rice, salsa and authentic garlic sauce.",
      price: 260,
      image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 25,
    },
    {
      categoryName: "BIRIYANI & MANDHI",
      name: "Tandoori Chicken Mandi",
      slug: "tandoori-chicken-mandi",
      description: "Smoky tandoori-spiced oven baked chicken quarter atop fragrant Arabic Mandhi rice served with midnight dips.",
      price: 260,
      image: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 25,
    },
    {
      categoryName: "BIRIYANI & MANDHI",
      name: "Fried Chicken Mandhi",
      slug: "fried-chicken-mandhi",
      description: "Crispy southern-spiced fried chicken paired with hot buttery Arabic mandhi rice and extra spicy garlic sauce.",
      price: 250,
      image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 25,
    },
    {
      categoryName: "BIRIYANI & MANDHI",
      name: "Beef Mandhi",
      slug: "beef-mandhi",
      description: "Melt-in-the-mouth slow-cooked succulent beef chunks served over rich broth-cooked fragrant mandhi rice.",
      price: 270,
      image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 30,
    },

    // ----------------------------------------------------
    // 2. SHAWARMA
    // ----------------------------------------------------
    {
      categoryName: "SHAWARMA",
      name: "Shawarma (Normal)",
      slug: "shawarma-normal",
      description: "Classic shredded slow-roasted chicken shawarma wrapped in kubbos with crunchy pickles and garlic sauce.",
      price: 120,
      image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 12,
    },
    {
      categoryName: "SHAWARMA",
      name: "Shawarma (Special)",
      slug: "shawarma-special",
      description: "Loaded juicy chicken shawarma with extra shredded chicken and rich signature mayonnaise blend.",
      price: 150,
      image: "https://images.unsplash.com/photo-1637806930600-37fa8892069d?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 12,
    },
    {
      categoryName: "SHAWARMA",
      name: "peri peri Chicken Shawarma",
      slug: "peri-peri-chicken-shawarma",
      description: "Spicy Peri-Peri marinated grilled chicken slivers rolled in warm bread with tangy garlic mayo.",
      price: 160,
      image: "https://images.unsplash.com/photo-1561651823-34feb02250e4?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 12,
    },
    {
      categoryName: "SHAWARMA",
      name: "Fried Chicken Swarma",
      slug: "fried-chicken-swarma",
      description: "Crispy crunchy southern fried chicken strips rolled in soft flatbread with creamy mayonnaise, lettuce, and secret spice dust.",
      price: 170,
      image: "https://images.unsplash.com/photo-1626777552726-4a6b54c97e46?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 15,
    },
    {
      categoryName: "SHAWARMA",
      name: "Rumali Chicken Shawarma",
      slug: "rumali-chicken-shawarma",
      description: "Juicy roasted chicken stuffed in ultra-soft, thin handkerchief Rumali Rotti with special midnight sauces.",
      price: 170,
      image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 15,
    },
    {
      categoryName: "SHAWARMA",
      name: "Jumbo Chicken Swarma",
      slug: "jumbo-chicken-swarma",
      description: "Massive portion of shredded marinated chicken rolled with creamy mayo and pickles in a jumbo roll.",
      price: 250,
      image: "https://images.unsplash.com/photo-1637806930600-37fa8892069d?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 15,
    },
    {
      categoryName: "SHAWARMA",
      name: "Rumali Chicken Shawarma (full meat)",
      slug: "rumali-chicken-shawarma-full-meat",
      description: "100% pure seasoned succulent chicken meat without any cabbage or fillers, tightly wrapped in soft rumali rotti.",
      price: 279,
      image: "https://images.unsplash.com/photo-1561651823-34feb02250e4?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 15,
    },
    {
      categoryName: "SHAWARMA",
      name: "Rumali Chicken (Jumbo Shawarma) With Cheese",
      slug: "rumali-chicken-jumbo-shawarma-with-cheese",
      description: "Monster-sized chicken shawarma inside soft rumali rotti loaded with melted mozzarella & cheddar cheese and mayo.",
      price: 299,
      image: "https://images.unsplash.com/photo-1529006557810-274b9b2fc783?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 18,
    },

    // ----------------------------------------------------
    // 3. CHICKEN & WINGS
    // ----------------------------------------------------
    {
      categoryName: "CHICKEN & WINGS",
      name: "Alfaham Chicken Full(With Salad And Mayyonise)",
      slug: "alfaham-chicken-full-with-salad-and-mayyonise",
      description: "Full whole chicken marinated in authentic Arabian herbs, slow grilled on charcoal. Served with fresh salad, pickled veggies, and garlic mayonnaise.",
      price: 529,
      image: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 30,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Alfaham Chicken Half",
      slug: "alfaham-chicken-half",
      description: "Half charcoal-grilled Arabian Alfaham chicken with aromatic spices and garlic mayo.",
      price: 300,
      image: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 25,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Alfaham Chicken Quarter",
      slug: "alfaham-chicken-quarter",
      description: "Quarter chicken charcoal-grilled in traditional Arabian red marinade with mayonnaise dip.",
      price: 170,
      image: "https://images.unsplash.com/photo-1599488615731-7e5c2823ff28?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: false,
      preparationTime: 20,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Grill Chicken Full",
      slug: "grill-chicken-full",
      description: "Full rotisserie spiced grilled chicken served with mayonnaise, fresh garden salad, and signature green chutney.",
      price: 530,
      image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 30,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Grill Chicken Half",
      slug: "grill-chicken-half",
      description: "Half juicy spiced grill chicken served with mayonnaise and refreshing green chutney.",
      price: 300,
      image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 25,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Grill Chicken Quarter",
      slug: "grill-chicken-quarter",
      description: "Quarter roasted juicy chicken with crisp skin, herbs and garlic mayonnaise.",
      price: 160,
      image: "https://images.unsplash.com/photo-1626082927389-6cd097cdc6ec?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: false,
      preparationTime: 20,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Fried Chicken (big size )",
      slug: "fried-chicken-big-size-1-pc",
      description: "1 jumbo piece of ultra-crispy southern golden fried chicken with secret blend of herbs and spices.",
      price: 85,
      image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 12,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Fried Chicken (big size) 3 pc",
      slug: "fried-chicken-big-size-3-pc",
      description: "3 large pieces of crunchy golden fried chicken, juicy on the inside, crispy on the outside.",
      price: 249,
      image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 15,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Fried Chicken 5 piece(big size)",
      slug: "fried-chicken-5-piece-big-size",
      description: "5 large jumbo crispy fried chicken pieces served with 2 delicious signature dipping sauces (With 2 Dips).",
      price: 399,
      image: "https://images.unsplash.com/photo-1569058242253-92a9c755a0ec?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 20,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Chicken Strips (6 pc)",
      slug: "chicken-strips-6-pc",
      description: "6 crunchy boneless chicken tender strips breaded with panko and seasoned to perfection. Served with creamy dip.",
      price: 200,
      image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 15,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Honey Chicken (Boneless)",
      slug: "honey-chicken-boneless",
      description: "Crispy boneless chicken tossed in a luscious sweet & spicy honey garlic glaze. Perfectly caramelized.",
      price: 200,
      image: "https://images.unsplash.com/photo-1527477321055-436158a2b0a5?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 15,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Hot&Spicy Honey Wings (6 pc)",
      slug: "hot-and-spicy-honey-wings-6-pc",
      description: "6 crispy golden wings tossed in fiery chili honey sauce, served with creamy mayonnaise dip.",
      price: 140,
      image: "https://images.unsplash.com/photo-1567620832903-9fc6debc209f?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 15,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Hot&Spicy Honey Wings (9 pc)",
      slug: "hot-and-spicy-honey-wings-9-pc",
      description: "9 jumbo wings coated in spicy honey pepper glaze, served with a generous cup of mayonnaise.",
      price: 199,
      image: "https://images.unsplash.com/photo-1527477321055-436158a2b0a5?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 18,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Pepper Chicken Dry (Boneless)",
      slug: "pepper-chicken-dry-boneless",
      description: "Tender boneless chicken morsels wok-fried with crushed black peppercorns, curry leaves, and green chilies.",
      price: 200,
      image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 15,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Kanthari Chicken Quarter",
      slug: "kanthari-chicken-quarter",
      description: "Quarter chicken marinated with spicy Kerala Kanthari chili paste and char-grilled with garlic dip.",
      price: 160,
      image: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: false,
      preparationTime: 20,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Kanthari Chicken Half",
      slug: "kanthari-chicken-half",
      description: "Half chicken infused with fiery green Kanthari peppers and roasted over red-hot coals.",
      price: 300,
      image: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 25,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Kanthari Chicken Full",
      slug: "kanthari-chicken-full",
      description: "Whole full chicken marinated with authentic bird's eye chili paste, grilled juicy and spicy to the bone.",
      price: 579,
      image: "https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 30,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Tandoori Chicken Quarter",
      slug: "tandoori-chicken-quarter",
      description: "Quarter leg piece steeped in rich tandoori yogurt marinade, smoked in clay tandoor.",
      price: 160,
      image: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: false,
      preparationTime: 20,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Tandoori Chicken Half",
      slug: "tandoori-chicken-half",
      description: "Half tandoori chicken cooked in tandoor until tender with charred edges, served with lemon & mint chutney.",
      price: 300,
      image: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 25,
    },
    {
      categoryName: "CHICKEN & WINGS",
      name: "Tandoori Chicken Full",
      slug: "tandoori-chicken-full",
      description: "Whole full chicken roasted in clay tandoor oven with signature red spices and aromatic herbs.",
      price: 550,
      image: "https://images.unsplash.com/photo-1610057099443-fde8c4d50f91?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 30,
    },

    // ----------------------------------------------------
    // 4. CHICKEN GRAVY & CURRY
    // ----------------------------------------------------
    {
      categoryName: "CHICKEN GRAVY & CURRY",
      name: "Butter Chicken Gravy (with boneless)",
      slug: "butter-chicken-gravy-with-boneless",
      description: "Velvety smooth, mild and creamy tomato-butter gravy simmered with tender boneless chicken pieces and dried fenugreek.",
      price: 200,
      image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 20,
    },
    {
      categoryName: "CHICKEN GRAVY & CURRY",
      name: "Chettinadu Chicken Gravy (with boneless)",
      slug: "chettinadu-chicken-gravy-with-boneless",
      description: "Fiery Karaikudi style roasted spice paste gravy cooked with boneless chicken, star anise, fennel, and fresh curry leaves.",
      price: 200,
      image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 20,
    },
    {
      categoryName: "CHICKEN GRAVY & CURRY",
      name: "Chilli Chicken Gravy (with boneless)",
      slug: "chilli-chicken-gravy-with-boneless",
      description: "Indo-Chinese style tender boneless chicken cubes tossed with diced capsicum, onions, and spicy dark soya-chili gravy.",
      price: 200,
      image: "https://images.unsplash.com/photo-1525755662778-989d0524087e?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 20,
    },
    {
      categoryName: "CHICKEN GRAVY & CURRY",
      name: "Garlic Chicken Gravy (with boneless)",
      slug: "garlic-chicken-gravy-with-boneless",
      description: "Aromatic thick curry infused with roasted golden garlic cloves, green chillies, and soft boneless chicken pieces.",
      price: 200,
      image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: false,
      preparationTime: 20,
    },
    {
      categoryName: "CHICKEN GRAVY & CURRY",
      name: "Ginger Chicken Gravy (with boneless)",
      slug: "ginger-chicken-gravy-with-boneless",
      description: "Zesty freshly julienned ginger gravy cooked with tender boneless chicken morsels and dark aromatic spices.",
      price: 200,
      image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: false,
      preparationTime: 20,
    },
    {
      categoryName: "CHICKEN GRAVY & CURRY",
      name: "Hydrabad Chicken Gravy (Boneless)",
      slug: "hydrabad-chicken-gravy-boneless",
      description: "Rich, aromatic Hyderabadi style slow-cooked boneless chicken curry in a thick spiced cashew-onion gravy.",
      price: 220,
      image: "https://images.unsplash.com/photo-1588166524941-3bf61a9c41db?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 20,
    },
    {
      categoryName: "CHICKEN GRAVY & CURRY",
      name: "Pepper Chicken Gravy (Boneless)",
      slug: "pepper-chicken-gravy-boneless",
      description: "Boneless chicken simmered in a luscious South Indian black pepper and curry leaf spiced dark gravy.",
      price: 220,
      image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 20,
    },

    // ----------------------------------------------------
    // 5. FRIED RICE & NOODLES
    // ----------------------------------------------------
    {
      categoryName: "FRIED RICE & NOODLES",
      name: "Chicken Fried Rice (With Mayonnaise)",
      slug: "chicken-fried-rice-with-mayonnaise",
      description: "Classic wok-tossed long-grain fried rice loaded with scrambled egg, shredded chicken, veggies, served with creamy mayonnaise.",
      price: 150,
      image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 15,
    },
    {
      categoryName: "FRIED RICE & NOODLES",
      name: "Chicken Noodles (With Mayonnaise)",
      slug: "chicken-noodles-with-mayonnaise",
      description: "Wok-tossed noodles with seasoned chicken slivers, spring onions, crunchy cabbage and garlic mayo.",
      price: 150,
      image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 15,
    },
    {
      categoryName: "FRIED RICE & NOODLES",
      name: "Egg Fried Rice",
      slug: "egg-fried-rice",
      description: "Aromatic wok fried rice with soft fluffy scrambled eggs, spring onions, carrots and mild Asian seasonings.",
      price: 130,
      image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 12,
    },
    {
      categoryName: "FRIED RICE & NOODLES",
      name: "Egg Noodles",
      slug: "egg-noodles",
      description: "Stir-fried street style noodles tossed with scrambled egg, sliced bell peppers, and savoury soy seasoning.",
      price: 130,
      image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 12,
    },
    {
      categoryName: "FRIED RICE & NOODLES",
      name: "Beef Fried Rice (With Mayonnaise)",
      slug: "beef-fried-rice-with-mayonnaise",
      description: "Hearty wok-fried rice with tender spiced beef chunks and scallions, served with creamy mayonnaise.",
      price: 150,
      image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 18,
    },
    {
      categoryName: "FRIED RICE & NOODLES",
      name: "Beef Noodles (With Mayonnaise)",
      slug: "beef-noodles-with-mayonnaise",
      description: "Hot tossed noodles with succulent seasoned beef slivers and crunchy vegetables, served with mayo.",
      price: 150,
      image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 18,
    },
    {
      categoryName: "FRIED RICE & NOODLES",
      name: "Chicken Schezwan Noodles",
      slug: "chicken-schezwan-noodles",
      description: "Fiery Schezwan style wok noodles tossed with spicy red chili paste, chicken shreds and crisp veggies.",
      price: 160,
      image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 15,
    },
    {
      categoryName: "FRIED RICE & NOODLES",
      name: "Schezwan Chicken Fired rice",
      slug: "schezwan-chicken-fried-rice",
      description: "Wok-tossed fiery Schezwan chicken fried rice loaded with egg, diced chicken, spring onions, served with mayonnaise.",
      price: 180,
      image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 18,
    },
    {
      categoryName: "FRIED RICE & NOODLES",
      name: "Schezwan Chicken Noodles",
      slug: "schezwan-chicken-noodles",
      description: "Spicy Schezwan wok noodles tossed with tender chicken shreds and crisp veggies, served with creamy mayo.",
      price: 180,
      image: "https://images.unsplash.com/photo-1585032226651-759b368d7246?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 18,
    },
    {
      categoryName: "FRIED RICE & NOODLES",
      name: "Schezwan Egg Fried rice",
      slug: "schezwan-egg-fried-rice",
      description: "Classic egg fried rice spiced with red Schezwan chili peppers, served with mayonnaise.",
      price: 150,
      image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: false,
      preparationTime: 15,
    },
    {
      categoryName: "FRIED RICE & NOODLES",
      name: "Schezwan Egg noodles",
      slug: "schezwan-egg-noodles",
      description: "Tossed noodles with scrambled eggs, shredded cabbage, carrots, and Schezwan chili oil, served with mayo.",
      price: 150,
      image: "https://images.unsplash.com/photo-1612927601601-6638404737ce?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: false,
      preparationTime: 15,
    },
    {
      categoryName: "FRIED RICE & NOODLES",
      name: "Schezwan Beef Fried Rice",
      slug: "schezwan-beef-fried-rice",
      description: "Hearty wok-fried rice with seasoned spiced beef chunks and spicy Schezwan peppers, served with mayonnaise.",
      price: 180,
      image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 20,
    },
    {
      categoryName: "FRIED RICE & NOODLES",
      name: "Schezwan Beef Noodles",
      slug: "schezwan-beef-noodles",
      description: "Steaming hot noodles tossed with succulent beef slivers and fiery Schezwan seasoning, served with mayo.",
      price: 180,
      image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: false,
      isPopular: true,
      preparationTime: 20,
    },

    // ----------------------------------------------------
    // 6. BURGERS & SANDWICHES
    // ----------------------------------------------------
    {
      categoryName: "BURGERS & SANDWICHES",
      name: "Cripsy Chicken Burger",
      slug: "cripsy-chicken-burger",
      description: "Golden fried crispy chicken breast fillet with melted cheese, crunchy lettuce, pickles and special burger sauce on toasted bun.",
      price: 180,
      image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 15,
    },
    {
      categoryName: "BURGERS & SANDWICHES",
      name: "Cripsy Chicken Sandwitch",
      slug: "cripsy-chicken-sandwitch",
      description: "Toasted golden sandwich stuffed with crispy chicken bites, coleslaw, cheese spread, and zesty secret dressing.",
      price: 160,
      image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 12,
    },
    {
      categoryName: "BURGERS & SANDWICHES",
      name: "No Bun Burger (Double Big Chicken)",
      slug: "no-bun-burger-double-big-chicken",
      description: "Low-carb keto specialty! Two massive crispy fried chicken patties sandwiching cheese, tomatoes, pickles and house sauce—zero bun.",
      price: 250,
      image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 18,
    },
    {
      categoryName: "BURGERS & SANDWICHES",
      name: "Veg Burger (With Patties)",
      slug: "veg-burger-with-patties",
      description: "Crispy seasoned vegetable patty layered with fresh lettuce, onions, tomato, cheese and tangy mayonnaise in a toasted bun.",
      price: 120,
      image: "https://images.unsplash.com/photo-1550547660-d9450f859349?w=800&auto=format&fit=crop&q=80",
      isVeg: true,
      isFeatured: false,
      isPopular: true,
      preparationTime: 15,
    },
    {
      categoryName: "BURGERS & SANDWICHES",
      name: "Veg Sandwich",
      slug: "veg-sandwich",
      description: "Golden toasted sandwich filled with crisp garden vegetables, melted butter, green chutney, and mild spices.",
      price: 120,
      image: "https://images.unsplash.com/photo-1528735602780-2552fd46c7af?w=800&auto=format&fit=crop&q=80",
      isVeg: true,
      isFeatured: false,
      isPopular: false,
      preparationTime: 12,
    },

    // ----------------------------------------------------
    // 7. PIZZA, FRIES & SIDES
    // ----------------------------------------------------
    {
      categoryName: "PIZZA, FRIES & SIDES",
      name: "Chicken Pizza",
      slug: "chicken-pizza",
      description: "Crispy baked crust topped with seasoned spiced chicken chunks, melting mozzarella cheese, bell peppers, and herb tomato sauce.",
      price: 180,
      image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 20,
    },
    {
      categoryName: "PIZZA, FRIES & SIDES",
      name: "Fried Chicken Pizza",
      slug: "fried-chicken-pizza",
      description: "Gourmet pizza loaded with crunchy golden fried chicken nuggets, melted cheddar & mozzarella, jalapenos, and smoky BBQ drizzle.",
      price: 199,
      image: "https://images.unsplash.com/photo-1565299624946-b28f40a0ae38?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 20,
    },
    {
      categoryName: "PIZZA, FRIES & SIDES",
      name: "Veg Pizza",
      slug: "veg-pizza",
      description: "Crispy crust pizza baked with rich marinara sauce, mozzarella cheese, bell peppers, onions, olives and sweet corn.",
      price: 130,
      image: "https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800&auto=format&fit=crop&q=80",
      isVeg: true,
      isFeatured: false,
      isPopular: true,
      preparationTime: 20,
    },
    {
      categoryName: "PIZZA, FRIES & SIDES",
      name: "Chicken Loaded Fries",
      slug: "chicken-loaded-fries",
      description: "Crispy golden french fries smothered in warm cheese sauce, spiced shredded chicken, jalapenos, and signature midnight fuel dressing.",
      price: 250,
      image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 15,
    },
    {
      categoryName: "PIZZA, FRIES & SIDES",
      name: "Chicken Loaded Fries (Only Chicken)",
      slug: "chicken-loaded-fries-only-chicken",
      description: "Extra heavy portion of pure seasoned crispy chicken chunks loaded with melting mozzarella, cheddar cheese sauce and garlic mayo—without potatoes.",
      price: 300,
      image: "https://images.unsplash.com/photo-1562967914-608f82629710?w=800&auto=format&fit=crop&q=80",
      isVeg: false,
      isFeatured: true,
      isPopular: true,
      preparationTime: 15,
    },
    {
      categoryName: "PIZZA, FRIES & SIDES",
      name: "French Fries",
      slug: "french-fries",
      description: "Crispy salted classic golden potato fries served hot with tomato ketchup.",
      price: 79,
      image: "https://images.unsplash.com/photo-1573080496219-bb080dd4f877?w=800&auto=format&fit=crop&q=80",
      isVeg: true,
      isFeatured: false,
      isPopular: true,
      preparationTime: 10,
    },
    {
      categoryName: "PIZZA, FRIES & SIDES",
      name: "Kubbos (1 pc)",
      slug: "kubbos-1-pc",
      description: "Authentic fluffy Arabic flatbread, freshly baked and served warm.",
      price: 20,
      image: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=800&auto=format&fit=crop&q=80",
      isVeg: true,
      isFeatured: false,
      isPopular: true,
      preparationTime: 5,
    },
    {
      categoryName: "PIZZA, FRIES & SIDES",
      name: "Rumali Rotti plane",
      slug: "rumali-rotti-plane",
      description: "Super thin, soft handkerchief bread cooked hot on an inverted tawa.",
      price: 29,
      image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80",
      isVeg: true,
      isFeatured: false,
      isPopular: true,
      preparationTime: 5,
    },
    {
      categoryName: "PIZZA, FRIES & SIDES",
      name: "Rumali Rotti Butter",
      slug: "rumali-rotti-butter",
      description: "Soft delicate rumali rotti brushed with rich melted butter.",
      price: 39,
      image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=800&auto=format&fit=crop&q=80",
      isVeg: true,
      isFeatured: false,
      isPopular: true,
      preparationTime: 5,
    },
    {
      categoryName: "PIZZA, FRIES & SIDES",
      name: "Extra Mayyonise",
      slug: "extra-mayyonise",
      description: "Rich, creamy house-crafted garlic mayonnaise dipping cup.",
      price: 20,
      image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80",
      isVeg: true,
      isFeatured: false,
      isPopular: false,
      preparationTime: 2,
    },
    {
      categoryName: "PIZZA, FRIES & SIDES",
      name: "Extra Cheese",
      slug: "extra-cheese",
      description: "Extra portion of hot melted cheddar and mozzarella cheese blend.",
      price: 20,
      image: "https://images.unsplash.com/photo-1618160702438-9b02ab6515c9?w=800&auto=format&fit=crop&q=80",
      isVeg: true,
      isFeatured: false,
      isPopular: false,
      preparationTime: 2,
    },
    {
      categoryName: "PIZZA, FRIES & SIDES",
      name: "Extra Tandoori Mayyonise",
      slug: "extra-tandoori-mayyonise",
      description: "Spicy and smoky tandoori-spiced flavored mayonnaise dipping cup.",
      price: 30,
      image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=800&auto=format&fit=crop&q=80",
      isVeg: true,
      isFeatured: false,
      isPopular: false,
      preparationTime: 2,
    },

    // ----------------------------------------------------
    // 8. BEVERAGES
    // ----------------------------------------------------
    {
      categoryName: "BEVERAGES",
      name: "Mojito Red (300 ml)",
      slug: "mojito-red-300-ml",
      description: "Refreshing sparkling red berry mojito with fresh mint leaves, lemon wedges, and crushed ice.",
      price: 99,
      image: "https://images.unsplash.com/photo-1551024709-8f23befc6f87?w=800&auto=format&fit=crop&q=80",
      isVeg: true,
      isFeatured: true,
      isPopular: true,
      preparationTime: 5,
    },
    {
      categoryName: "BEVERAGES",
      name: "Blue Curacao Mojito (300ml)",
      slug: "blue-curacao-mojito-300ml",
      description: "Vibrant tropical blue curacao citrus mocktail with fresh mint, lemon fizz, and ice.",
      price: 99,
      image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=80",
      isVeg: true,
      isFeatured: true,
      isPopular: true,
      preparationTime: 5,
    },
    {
      categoryName: "BEVERAGES",
      name: "Green Mojito (300ml)",
      slug: "green-mojito-300ml",
      description: "Crisp green apple and zesty mint mojito infused with sparkling soda and lime.",
      price: 99,
      image: "https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?w=800&auto=format&fit=crop&q=80",
      isVeg: true,
      isFeatured: true,
      isPopular: true,
      preparationTime: 5,
    },
  ];

  const productMap = new Map<string, string>();
  for (const item of productsData) {
    const categoryId = categoryMap.get(item.categoryName);
    if (!categoryId) {
      console.warn(`Category not found: ${item.categoryName}`);
      continue;
    }

    const created = await prisma.product.create({
      data: {
        categoryId,
        name: item.name,
        slug: item.slug,
        description: item.description,
        price: item.price,
        image: item.image,
        isVeg: item.isVeg,
        isAvailable: true,
        isFeatured: item.isFeatured,
        isPopular: item.isPopular,
        preparationTime: item.preparationTime,
      },
    });
    productMap.set(item.name, created.id);
  }
  console.log(`✅ ${productsData.length} Products seeded successfully`);

  // 7. Seed Daily Combos using actual products
  const combo1 = await prisma.combo.create({
    data: {
      comboNumber: 1,
      name: "Combo 1 - Biriyani Feast",
      description: "Hydrabad Alfaham Chicken Biriyani served with Rumali Rotti Butter, Butter Chicken Gravy and chilled Mojito Red.",
      image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=800&auto=format&fit=crop&q=80",
      servingPeople: "Serves 2-3 People",
      price: 555,
      originalPrice: 668,
      isActive: true,
      displayOrder: 1,
      items: {
        create: [
          { productId: productMap.get("Hydrabad Alfaham Chicken Biriyani"), customItemName: "Hydrabad Alfaham Chicken Biriyani", quantity: 1 },
          { productId: productMap.get("Butter Chicken Gravy (with boneless)"), customItemName: "Butter Chicken Gravy", quantity: 1 },
          { productId: productMap.get("Rumali Rotti Butter"), customItemName: "Rumali Rotti Butter", quantity: 3 },
          { productId: productMap.get("Mojito Red (300 ml)"), customItemName: "Mojito Red", quantity: 1 },
        ],
      },
    },
  });

  const combo2 = await prisma.combo.create({
    data: {
      comboNumber: 2,
      name: "Combo 2 - Schezwan Wok Feast",
      description: "Schezwan Chicken Fried Rice, Schezwan Chicken Noodles, Hot & Spicy Honey Wings (6 pc) and Mayonnaise.",
      image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=800&auto=format&fit=crop&q=80",
      servingPeople: "Serves 3-4 People",
      price: 555,
      originalPrice: 640,
      isActive: true,
      displayOrder: 2,
      items: {
        create: [
          { productId: productMap.get("Schezwan Chicken Fired rice"), customItemName: "Schezwan Chicken Fried Rice", quantity: 1 },
          { productId: productMap.get("Schezwan Chicken Noodles"), customItemName: "Schezwan Chicken Noodles", quantity: 1 },
          { productId: productMap.get("Hot&Spicy Honey Wings (6 pc)"), customItemName: "Hot & Spicy Honey Wings (6 pc)", quantity: 1 },
          { customItemName: "Mayonnaise Dip", quantity: 2 },
        ],
      },
    },
  });

  const combo3 = await prisma.combo.create({
    data: {
      comboNumber: 3,
      name: "Combo 3 - Shawarma & Burger Platter",
      description: "Jumbo Chicken Shawarma, Cripsy Chicken Burger, Chicken Pizza and Blue Curacao Mojito.",
      image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=800&auto=format&fit=crop&q=80",
      servingPeople: "Serves 2-3 People",
      price: 555,
      originalPrice: 709,
      isActive: true,
      displayOrder: 3,
      items: {
        create: [
          { productId: productMap.get("Jumbo Chicken Swarma"), customItemName: "Jumbo Chicken Shawarma", quantity: 1 },
          { productId: productMap.get("Cripsy Chicken Burger"), customItemName: "Cripsy Chicken Burger", quantity: 1 },
          { productId: productMap.get("Chicken Pizza"), customItemName: "Chicken Pizza", quantity: 1 },
        ],
      },
    },
  });
  console.log(`✅ 3 Daily Combos seeded`);

  console.log("🌟 Midnight Fuel Menu Database Seeding Completed Successfully!");
}

main()
  .catch((e) => {
    console.error("❌ Seeding failed:", e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
